//! Mirrors, pacman and the AUR.

use crate::step::Step;
use crate::system::Cmd;
use crate::tweak::{Availability, Group, OptionValue, Tweak, TweakOption};

/// Always fits: every Arch machine has pacman.
fn always(_: &mut dyn crate::system::System) -> Availability {
    Availability::Yes
}

/// The mirror list, refreshed by reflector and kept fresh by its timer.
///
/// The check greps for reflector's own header rather than testing that the file merely
/// exists: every stock Arch install already has a non-empty `mirrorlist`, so `test -s`
/// would report this tweak as permanently applied and never run. The file's undo comes
/// from `Step::FileRewritten`, which captures its prior content itself; there is no
/// `mirrorlist.pacnew` to fall back to, since nothing here makes pacman produce one.
pub fn mirrors(country: &str, count: u32) -> Tweak {
    let run = Cmd::new(
        "reflector",
        ["--country", country, "--latest", &count.to_string(), "--sort", "rate", "--save", MIRRORLIST],
    )
    .root();
    Tweak {
        id: "mirrors",
        group: Group::Packages,
        options: vec![
            TweakOption { key: "mirrors.country", value: OptionValue::Text(country.to_owned()) },
            TweakOption { key: "mirrors.count", value: OptionValue::Count(count) },
        ],
        steps: vec![
            Step::PackageInstalled { package: "reflector" },
            Step::FileRewritten {
                path: MIRRORLIST,
                run,
                check: Cmd::new("sh", ["-c", "grep -q 'generated by Reflector' /etc/pacman.d/mirrorlist"]),
                label: "reflector",
            },
            Step::ServiceEnabled { unit: "reflector.timer" },
        ],
        applies_to: always,
    }
}

const MIRRORLIST: &str = "/etc/pacman.d/mirrorlist";

/// The pacman options the community recommends.
///
/// `Color` and `VerbosePkgLists` are valueless pacman directives — the line is just the
/// key, with no `=` — so they carry an empty `value`; `ConfOption` and `conf::set_option`
/// treat an empty value as a bare directive rather than `key = `.
pub fn pacman_options(parallel: u32) -> Tweak {
    Tweak {
        id: "pacman-options",
        group: Group::Packages,
        options: vec![TweakOption { key: "pacman.parallel", value: OptionValue::Count(parallel) }],
        steps: vec![
            Step::ConfOption { file: PACMAN_CONF, key: "ParallelDownloads", value: parallel.to_string() },
            Step::ConfOption { file: PACMAN_CONF, key: "Color", value: String::new() },
            Step::ConfOption { file: PACMAN_CONF, key: "VerbosePkgLists", value: String::new() },
        ],
        applies_to: always,
    }
}

/// The 32-bit repository, needed by Steam and by some drivers.
///
/// This one is a section rather than an option, so `ConfOption` cannot express it: the
/// check asks pacman itself whether the repository is there. The undo comes from the
/// file's own captured content, via `Step::FileRewritten`, rather than from a `sed`
/// command trying to cut the section back out — that could never restore what it never
/// recorded, and risked leaving a stray blank line behind.
pub fn multilib() -> Tweak {
    Tweak {
        id: "multilib",
        group: Group::Packages,
        options: Vec::new(),
        steps: vec![Step::FileRewritten {
            path: PACMAN_CONF,
            run: Cmd::new(
                "sh",
                ["-c", "printf '\\n[multilib]\\nInclude = /etc/pacman.d/mirrorlist\\n' >> /etc/pacman.conf"],
            )
            .root(),
            check: Cmd::new("sh", ["-c", "pacman-conf --repo-list | grep -qx multilib"]),
            label: "multilib",
        }],
        applies_to: always,
    }
}

/// An AUR helper, built from the AUR itself.
pub fn aur_helper(helper: &'static str) -> Tweak {
    Tweak {
        id: "aur-helper",
        group: Group::Packages,
        options: vec![TweakOption {
            key: "aur.helper",
            value: OptionValue::Choice { chosen: usize::from(helper == "yay"), options: vec!["aur.paru", "aur.yay"] },
        }],
        steps: vec![
            Step::PackageInstalled { package: "base-devel" },
            Step::PackageInstalled { package: "git" },
            Step::CommandRun {
                run: Cmd::new("sh", ["-c", &build_script(helper)]),
                // `command` is a shell builtin, not a binary `RealSystem::run` could exec
                // directly, so the check runs it through a shell, the same way the
                // `multilib` check does.
                check: Cmd::new("sh", ["-c", &format!("command -v {helper}")]),
                undo: Cmd::new("pacman", ["-Rns", "--noconfirm", helper]).root(),
                label: helper,
            },
        ],
        applies_to: always,
    }
}

/// Keeps the package cache from growing without end.
pub fn cache_cleanup() -> Tweak {
    Tweak {
        id: "cache-cleanup",
        group: Group::Packages,
        options: Vec::new(),
        steps: vec![
            Step::PackageInstalled { package: "pacman-contrib" },
            Step::ServiceEnabled { unit: "paccache.timer" },
        ],
        applies_to: always,
    }
}

const PACMAN_CONF: &str = "/etc/pacman.conf";

/// Cloning the helper's package and building it, in one shell line.
///
/// `helper` is interpolated into this shell command unescaped, so it must stay a
/// trusted literal — one of the catalog's own `"paru"`/`"yay"` — never text a person typed.
fn build_script(helper: &str) -> String {
    format!(
        "cd \"$(mktemp -d)\" && git clone https://aur.archlinux.org/{helper}.git && cd {helper} && makepkg -si --noconfirm"
    )
}
