use super::*;
use crate::step::Touch;
use crate::system::{FakeSystem, Output, System};
use crate::tweak::{Availability, Group, OptionValue, TweakOption, TweakState};

#[test]
fn every_tweak_has_an_identity_of_its_own() {
    let mut ids: Vec<&str> = all().iter().map(|tweak| tweak.id).collect();
    ids.sort_unstable();
    let mut unique = ids.clone();
    unique.dedup();
    assert_eq!(ids, unique, "two tweaks share an id");
}

#[test]
fn the_packages_group_has_its_five_tweaks() {
    let ids: Vec<&str> = in_group(Group::Packages).iter().map(|tweak| tweak.id).collect();
    assert_eq!(ids, ["mirrors", "pacman-options", "multilib", "aur-helper", "cache-cleanup"]);
}

#[test]
fn the_mirror_tweak_installs_reflector_writes_the_list_and_turns_on_the_timer() {
    let tweak = packages::mirrors("TR", 10);
    assert_eq!(
        tweak.touches(),
        vec![
            Touch::Package("reflector".into()),
            Touch::File("/etc/pacman.d/mirrorlist".into()),
            Touch::Command("reflector".into()),
            Touch::Service("reflector.timer".into()),
        ]
    );
}

#[test]
fn the_chosen_country_and_count_reach_the_command() {
    let mut system = FakeSystem::new();
    system.answer("pacman -Q reflector", Output { code: 0, stdout: "reflector 2023".into(), stderr: String::new() });
    system.answer(
        "sh -c grep -q 'generated by Reflector' /etc/pacman.d/mirrorlist",
        Output { code: 1, stdout: String::new(), stderr: String::new() },
    );
    system.answer(
        "systemctl is-enabled reflector.timer",
        Output { code: 1, stdout: String::new(), stderr: String::new() },
    );
    system.answer(
        "systemctl is-active reflector.timer",
        Output { code: 1, stdout: String::new(), stderr: String::new() },
    );
    let mut journal = crate::state::Journal::default();

    let _ = packages::mirrors("DE", 20).apply(&mut system, &mut journal, std::path::Path::new("/tmp/state"));

    let call = system.calls().iter().find(|call| call.contains("reflector --country")).expect("reflector runs");
    assert!(call.contains("--country DE"), "{call}");
    assert!(call.contains("--latest 20"), "{call}");
}

#[test]
fn pacman_options_are_off_on_a_fresh_file_and_applied_after_a_run() {
    let mut system = FakeSystem::new();
    system.file("/etc/pacman.conf", "[options]\n#ParallelDownloads = 5\n#Color\n");
    let tweak = packages::pacman_options(5);
    let mut journal = crate::state::Journal::default();

    assert_eq!(tweak.state(&mut system).expect("the file reads"), TweakState::Off);
    tweak.apply(&mut system, &mut journal, std::path::Path::new("/tmp/state")).expect("the file is written");
    assert_eq!(tweak.state(&mut system).expect("the file reads"), TweakState::Applied);
}

#[test]
fn the_aur_helper_choice_decides_which_one_is_built() {
    assert!(
        packages::aur_helper("paru")
            .touches()
            .iter()
            .any(|touch| matches!(touch, Touch::Command(name) if name == "paru"))
    );
    assert!(
        packages::aur_helper("yay")
            .touches()
            .iter()
            .any(|touch| matches!(touch, Touch::Command(name) if name == "yay"))
    );
}

#[test]
fn every_tweak_and_group_reads_fully_in_both_languages() {
    let env = crate::locales::env();
    assert_eq!(env.diagnostics(), &[]);
    assert_eq!(env.i18n().missing_keys("tr", "en"), Vec::<String>::new());

    // Each language must carry the key itself: a borrowed English text would read on screen,
    // but `has` says `false` for it, which is what keeps the Turkish file complete.
    let reads = |key: &str| {
        for code in ["en", "tr"] {
            assert!(env.i18n().has(code, key), "`{key}` has no text in `{code}`");
        }
    };

    for group in Group::ALL {
        reads(&format!("group.{}", group.key()));
    }
    for tweak in all() {
        reads(&format!("tweak.{}.title", tweak.id));
        reads(&format!("tweak.{}.summary", tweak.id));
        for option in &tweak.options {
            reads(&format!("option.{}", option.key));
        }
    }
}

#[test]
fn the_maintenance_group_has_its_three_tweaks() {
    let ids: Vec<&str> = in_group(Group::Maintenance).iter().map(|tweak| tweak.id).collect();
    assert_eq!(ids, ["ssd-trim", "journal-limit", "time-sync"]);
}

fn ok(stdout: &str) -> Output {
    Output { code: 0, stdout: stdout.into(), stderr: String::new() }
}

fn no() -> Output {
    Output { code: 1, stdout: String::new(), stderr: String::new() }
}

#[test]
fn ssd_trim_touches_only_the_fstrim_timer() {
    assert_eq!(maintenance::ssd_trim().touches(), vec![Touch::Service("fstrim.timer".into())]);
}

#[test]
fn ssd_trim_is_off_until_the_timer_runs_and_applied_afterwards() {
    let mut system = FakeSystem::new();
    system.answer("lsblk -dno NAME,ROTA", ok("nvme0n1 0\nsda 1"));
    system.answer("systemctl is-enabled fstrim.timer", no());
    system.answer("systemctl is-active fstrim.timer", no());
    let tweak = maintenance::ssd_trim();
    assert_eq!(tweak.state(&mut system).expect("the fake answers"), TweakState::Off);

    system.answer("systemctl is-enabled fstrim.timer", ok("enabled"));
    system.answer("systemctl is-active fstrim.timer", ok("active"));
    assert_eq!(tweak.state(&mut system).expect("the fake answers"), TweakState::Applied);
}

#[test]
fn applying_ssd_trim_enables_and_starts_the_timer_as_root() {
    let mut system = FakeSystem::new();
    system.answer("lsblk -dno NAME,ROTA", ok("nvme0n1 0"));
    system.answer("systemctl is-enabled fstrim.timer", no());
    system.answer("systemctl is-active fstrim.timer", no());
    system.answer("sudo systemctl enable --now fstrim.timer", ok(""));
    let mut journal = crate::state::Journal::default();

    maintenance::ssd_trim().apply(&mut system, &mut journal, std::path::Path::new("/tmp/state")).expect("it runs");

    assert!(
        system.calls().iter().any(|call| call == "sudo systemctl enable --now fstrim.timer"),
        "{:?}",
        system.calls()
    );
}

#[test]
fn ssd_trim_fits_a_machine_with_a_non_rotational_disk() {
    let mut system = FakeSystem::new();
    system.answer("lsblk -dno NAME,ROTA", ok("sda 1\nnvme0n1 0"));
    assert_eq!((maintenance::ssd_trim().applies_to)(&mut system), Availability::Yes);
}

#[test]
fn ssd_trim_does_not_fit_a_machine_with_spinning_disks_only() {
    let mut system = FakeSystem::new();
    system.answer("lsblk -dno NAME,ROTA", ok("sda 1\nsdb 1"));
    assert_eq!((maintenance::ssd_trim().applies_to)(&mut system), Availability::No("unavailable.no-ssd"));
    assert_eq!(
        maintenance::ssd_trim().state(&mut system).expect("nothing else runs"),
        TweakState::Unavailable("unavailable.no-ssd")
    );
}

#[test]
fn zram_and_loop_devices_do_not_count_as_an_ssd() {
    let mut system = FakeSystem::new();
    system.answer("lsblk -dno NAME,ROTA", ok("zram0 0\nloop0 0\nvda 1"));
    assert_eq!((maintenance::ssd_trim().applies_to)(&mut system), Availability::No("unavailable.no-ssd"));
}

#[test]
fn ssd_trim_does_not_fit_when_lsblk_cannot_answer() {
    let mut system = FakeSystem::new();
    assert_eq!((maintenance::ssd_trim().applies_to)(&mut system), Availability::No("unavailable.no-ssd"));
}

const JOURNAL_DROP_IN: &str = "/etc/systemd/journald.conf.d/50-quvyta-tools.conf";

#[test]
fn the_journal_limit_touches_only_its_own_drop_in() {
    assert_eq!(maintenance::journal_limit(500).touches(), vec![Touch::File(JOURNAL_DROP_IN.into())]);
}

#[test]
fn the_journal_limit_is_off_applied_or_changed_by_what_the_drop_in_holds() {
    let mut system = FakeSystem::new();
    let tweak = maintenance::journal_limit(500);
    assert_eq!(tweak.state(&mut system).expect("the file reads"), TweakState::Off);

    system.file(JOURNAL_DROP_IN, "[Journal]\nSystemMaxUse=500M\n");
    assert_eq!(tweak.state(&mut system).expect("the file reads"), TweakState::Applied);

    system.file(JOURNAL_DROP_IN, "[Journal]\nSystemMaxUse=2G\n");
    assert_eq!(
        tweak.state(&mut system).expect("the file reads"),
        TweakState::Changed("[Journal]\nSystemMaxUse=2G\n".into())
    );
}

#[test]
fn applying_the_journal_limit_writes_the_chosen_size_in_megabytes() {
    let mut system = FakeSystem::new();
    let mut journal = crate::state::Journal::default();

    maintenance::journal_limit(200)
        .apply(&mut system, &mut journal, std::path::Path::new("/tmp/state"))
        .expect("the file is written");

    assert_eq!(
        system.read(std::path::Path::new(JOURNAL_DROP_IN)).expect("the fake reads"),
        Some("[Journal]\nSystemMaxUse=200M\n".into())
    );
    assert!(system.calls().is_empty(), "a drop-in needs no command: {:?}", system.calls());
}

#[test]
fn the_journal_limit_offers_its_size_as_an_option_and_fits_every_machine() {
    let tweak = maintenance::journal_limit(500);
    assert_eq!(tweak.options, vec![TweakOption { key: "journal.max-use", value: OptionValue::Count(500) }]);
    assert_eq!((tweak.applies_to)(&mut FakeSystem::new()), Availability::Yes);
}

#[test]
fn time_sync_touches_only_the_timesyncd_service() {
    assert_eq!(maintenance::time_sync().touches(), vec![Touch::Service("systemd-timesyncd.service".into())]);
}

#[test]
fn time_sync_is_off_until_the_service_runs_and_applied_afterwards() {
    let mut system = FakeSystem::new();
    system.answer("systemctl is-enabled systemd-timesyncd.service", no());
    system.answer("systemctl is-active systemd-timesyncd.service", no());
    let tweak = maintenance::time_sync();
    assert_eq!(tweak.state(&mut system).expect("the fake answers"), TweakState::Off);

    system.answer("systemctl is-enabled systemd-timesyncd.service", ok("enabled"));
    system.answer("systemctl is-active systemd-timesyncd.service", ok("active"));
    assert_eq!(tweak.state(&mut system).expect("the fake answers"), TweakState::Applied);
}

#[test]
fn applying_time_sync_enables_and_starts_the_service_as_root() {
    let mut system = FakeSystem::new();
    system.answer("systemctl is-enabled systemd-timesyncd.service", no());
    system.answer("systemctl is-active systemd-timesyncd.service", no());
    system.answer("sudo systemctl enable --now systemd-timesyncd.service", ok(""));
    let mut journal = crate::state::Journal::default();

    maintenance::time_sync().apply(&mut system, &mut journal, std::path::Path::new("/tmp/state")).expect("it runs");

    assert!(
        system.calls().iter().any(|call| call == "sudo systemctl enable --now systemd-timesyncd.service"),
        "{:?}",
        system.calls()
    );
}

#[test]
fn time_sync_fits_when_no_other_time_service_is_installed() {
    let mut system = FakeSystem::new();
    assert_eq!((maintenance::time_sync().applies_to)(&mut system), Availability::Yes);
    assert_eq!(
        system.calls(),
        ["pacman -Q chrony", "pacman -Q ntp", "pacman -Q openntpd"],
        "every other daemon is asked about"
    );
}

#[test]
fn time_sync_steps_aside_when_chrony_keeps_the_clock() {
    let mut system = FakeSystem::new();
    system.answer("pacman -Q chrony", ok("chrony 4.5-1"));
    assert_eq!((maintenance::time_sync().applies_to)(&mut system), Availability::No("unavailable.other-time-service"));
    assert_eq!(
        maintenance::time_sync().state(&mut system).expect("nothing else runs"),
        TweakState::Unavailable("unavailable.other-time-service")
    );
}

#[test]
fn time_sync_steps_aside_when_openntpd_keeps_the_clock() {
    let mut system = FakeSystem::new();
    system.answer("pacman -Q openntpd", ok("openntpd 6.8p1-1"));
    assert_eq!((maintenance::time_sync().applies_to)(&mut system), Availability::No("unavailable.other-time-service"));
}

#[test]
fn every_unavailable_reason_in_the_catalog_reads_in_both_languages() {
    let env = crate::locales::env();
    for key in ["unavailable.no-ssd", "unavailable.other-time-service", "unavailable.no-openssh"] {
        for code in ["en", "tr"] {
            assert!(env.i18n().has(code, key), "`{key}` has no text in `{code}`");
        }
    }
}

#[test]
fn the_security_group_has_its_two_tweaks() {
    let ids: Vec<&str> = in_group(Group::Security).iter().map(|tweak| tweak.id).collect();
    assert_eq!(ids, ["firewall", "ssh-hardening"]);
}

#[test]
fn the_sidebar_order_and_the_catalog_order_agree() {
    let groups: Vec<Group> = all().iter().map(|tweak| tweak.group).collect();
    let mut sorted = groups.clone();
    sorted.sort_by_key(|group| Group::ALL.iter().position(|g| g == group));
    assert_eq!(groups, sorted, "the catalog lists its groups in sidebar order");
}

const UFW_CHECK: &str = "sh -c grep -qx 'ENABLED=yes' /etc/ufw/ufw.conf";

#[test]
fn the_firewall_installs_ufw_turns_it_on_and_enables_its_service() {
    assert_eq!(
        security::firewall().touches(),
        vec![Touch::Package("ufw".into()), Touch::Command("ufw".into()), Touch::Service("ufw.service".into())]
    );
}

#[test]
fn the_firewall_is_off_until_everything_runs_and_applied_afterwards() {
    let mut system = FakeSystem::new();
    system.answer("pacman -Q ufw", no());
    system.answer(UFW_CHECK, no());
    system.answer("systemctl is-enabled ufw.service", no());
    system.answer("systemctl is-active ufw.service", no());
    let tweak = security::firewall();
    assert_eq!(tweak.state(&mut system).expect("the fake answers"), TweakState::Off);

    system.answer("pacman -Q ufw", ok("ufw 0.36.2-4"));
    system.answer(UFW_CHECK, ok(""));
    system.answer("systemctl is-enabled ufw.service", ok("enabled"));
    system.answer("systemctl is-active ufw.service", ok("active"));
    assert_eq!(tweak.state(&mut system).expect("the fake answers"), TweakState::Applied);
}

#[test]
fn applying_the_firewall_runs_every_step_as_root_and_checks_without_root() {
    let mut system = FakeSystem::new();
    system.answer("pacman -Q ufw", no());
    system.answer(UFW_CHECK, no());
    system.answer("systemctl is-enabled ufw.service", no());
    system.answer("systemctl is-active ufw.service", no());
    system.answer("sudo pacman -S --needed --noconfirm ufw", ok(""));
    system.answer("sudo ufw --force enable", ok("Firewall is active and enabled on system startup"));
    system.answer("sudo systemctl enable --now ufw.service", ok(""));
    let mut journal = crate::state::Journal::default();

    security::firewall().apply(&mut system, &mut journal, std::path::Path::new("/tmp/state")).expect("it runs");

    let root_calls: Vec<&String> = system.calls().iter().filter(|call| call.starts_with("sudo ")).collect();
    assert_eq!(
        root_calls,
        [
            "sudo pacman -S --needed --noconfirm ufw",
            "sudo ufw --force enable",
            "sudo systemctl enable --now ufw.service"
        ]
    );
    assert!(system.calls().contains(&UFW_CHECK.to_owned()), "{:?}", system.calls());
}

#[test]
fn the_firewall_fits_every_machine_and_has_nothing_to_set() {
    let tweak = security::firewall();
    assert_eq!((tweak.applies_to)(&mut FakeSystem::new()), Availability::Yes);
    assert!(tweak.options.is_empty());
}

const SSHD_DROP_IN: &str = "/etc/ssh/sshd_config.d/50-quvyta-tools.conf";
const SSHD_CONTENT: &str = "PasswordAuthentication no\nPermitRootLogin no\n";

#[test]
fn ssh_hardening_touches_only_its_own_drop_in() {
    assert_eq!(security::ssh_hardening().touches(), vec![Touch::File(SSHD_DROP_IN.into())]);
}

#[test]
fn ssh_hardening_is_off_applied_or_changed_by_what_the_drop_in_holds() {
    let mut system = FakeSystem::new();
    system.answer("pacman -Q openssh", ok("openssh 10.5p1-1"));
    let tweak = security::ssh_hardening();
    assert_eq!(tweak.state(&mut system).expect("the file reads"), TweakState::Off);

    system.file(SSHD_DROP_IN, SSHD_CONTENT);
    assert_eq!(tweak.state(&mut system).expect("the file reads"), TweakState::Applied);

    system.file(SSHD_DROP_IN, "PermitRootLogin yes\n");
    assert_eq!(tweak.state(&mut system).expect("the file reads"), TweakState::Changed("PermitRootLogin yes\n".into()));
}

#[test]
fn applying_ssh_hardening_writes_the_drop_in_and_runs_no_command() {
    let mut system = FakeSystem::new();
    let mut journal = crate::state::Journal::default();

    security::ssh_hardening()
        .apply(&mut system, &mut journal, std::path::Path::new("/tmp/state"))
        .expect("the file is written");

    assert_eq!(system.read(std::path::Path::new(SSHD_DROP_IN)).expect("the fake reads"), Some(SSHD_CONTENT.into()));
    assert!(system.calls().is_empty(), "no sshd reload, no command at all: {:?}", system.calls());
}

#[test]
fn ssh_hardening_fits_only_a_machine_with_openssh() {
    let mut system = FakeSystem::new();
    assert_eq!((security::ssh_hardening().applies_to)(&mut system), Availability::No("unavailable.no-openssh"));
    assert_eq!(
        security::ssh_hardening().state(&mut system).expect("nothing else runs"),
        TweakState::Unavailable("unavailable.no-openssh")
    );
    assert_eq!(system.calls(), ["pacman -Q openssh", "pacman -Q openssh"]);

    system.answer("pacman -Q openssh", ok("openssh 10.5p1-1"));
    assert_eq!((security::ssh_hardening().applies_to)(&mut system), Availability::Yes);
}
